/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as HowRouteImport } from './routes/how'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AppBookingsRouteImport } from './routes/_app/bookings'
import { Route as AppBusinessRouteImport } from './routes/_app/business'
import { Route as AppEnquiriesRouteRouteImport } from './routes/_app/enquiries/route'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppLabRouteImport } from './routes/_app/lab'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTrustRouteRouteImport } from './routes/_app/trust/route'
import { Route as BookBookingIdRouteImport } from './routes/book/$bookingId'
import { Route as QEnquiryIdRouteImport } from './routes/q/$enquiryId'
import { Route as AppEnquiriesIndexRouteImport } from './routes/_app/enquiries/index'
import { Route as AppEnquiriesEnquiryIdRouteImport } from './routes/_app/enquiries/$enquiryId'
import { Route as AppTrustIndexRouteImport } from './routes/_app/trust/index'
import { Route as AppTrustAccessRouteImport } from './routes/_app/trust/access'
import { Route as AppTrustAuditRouteImport } from './routes/_app/trust/audit'
import { Route as AppTrustAutomationRouteImport } from './routes/_app/trust/automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesRouteRoute = AppEnquiriesRouteRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrustRouteRoute = AppTrustRouteRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AppRoute,
} as any)
const BookBookingIdRoute = BookBookingIdRouteImport.update({
  id: '/book/$bookingId',
  path: '/book/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const QEnquiryIdRoute = QEnquiryIdRouteImport.update({
  id: '/q/$enquiryId',
  path: '/q/$enquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEnquiriesIndexRoute = AppEnquiriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEnquiriesRouteRoute,
} as any)
const AppEnquiriesEnquiryIdRoute = AppEnquiriesEnquiryIdRouteImport.update({
  id: '/$enquiryId',
  path: '/$enquiryId',
  getParentRoute: () => AppEnquiriesRouteRoute,
} as any)
const AppTrustIndexRoute = AppTrustIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrustRouteRoute,
} as any)
const AppTrustAccessRoute = AppTrustAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppTrustRouteRoute,
} as any)
const AppTrustAuditRoute = AppTrustAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppTrustRouteRoute,
} as any)
const AppTrustAutomationRoute = AppTrustAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppTrustRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/early-access': typeof EarlyAccessRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/enquiries': typeof AppEnquiriesRouteRouteWithChildren
  '/trust': typeof AppTrustRouteRouteWithChildren
  '/bookings': typeof AppBookingsRoute
  '/business': typeof AppBusinessRoute
  '/insights': typeof AppInsightsRoute
  '/lab': typeof AppLabRoute
  '/settings': typeof AppSettingsRoute
  '/book/$bookingId': typeof BookBookingIdRoute
  '/q/$enquiryId': typeof QEnquiryIdRoute
  '/enquiries/$enquiryId': typeof AppEnquiriesEnquiryIdRoute
  '/trust/access': typeof AppTrustAccessRoute
  '/trust/audit': typeof AppTrustAuditRoute
  '/trust/automation': typeof AppTrustAutomationRoute
  '/enquiries/': typeof AppEnquiriesIndexRoute
  '/trust/': typeof AppTrustIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/early-access': typeof EarlyAccessRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/bookings': typeof AppBookingsRoute
  '/business': typeof AppBusinessRoute
  '/insights': typeof AppInsightsRoute
  '/lab': typeof AppLabRoute
  '/settings': typeof AppSettingsRoute
  '/book/$bookingId': typeof BookBookingIdRoute
  '/q/$enquiryId': typeof QEnquiryIdRoute
  '/enquiries/$enquiryId': typeof AppEnquiriesEnquiryIdRoute
  '/trust/access': typeof AppTrustAccessRoute
  '/trust/audit': typeof AppTrustAuditRoute
  '/trust/automation': typeof AppTrustAutomationRoute
  '/enquiries': typeof AppEnquiriesIndexRoute
  '/trust': typeof AppTrustIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/early-access': typeof EarlyAccessRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/_app/enquiries': typeof AppEnquiriesRouteRouteWithChildren
  '/_app/trust': typeof AppTrustRouteRouteWithChildren
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/lab': typeof AppLabRoute
  '/_app/settings': typeof AppSettingsRoute
  '/book/$bookingId': typeof BookBookingIdRoute
  '/q/$enquiryId': typeof QEnquiryIdRoute
  '/_app/enquiries/$enquiryId': typeof AppEnquiriesEnquiryIdRoute
  '/_app/trust/access': typeof AppTrustAccessRoute
  '/_app/trust/audit': typeof AppTrustAuditRoute
  '/_app/trust/automation': typeof AppTrustAutomationRoute
  '/_app/enquiries/': typeof AppEnquiriesIndexRoute
  '/_app/trust/': typeof AppTrustIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/early-access'
    | '/how'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/updates'
    | '/enquiries'
    | '/trust'
    | '/bookings'
    | '/business'
    | '/insights'
    | '/lab'
    | '/settings'
    | '/book/$bookingId'
    | '/q/$enquiryId'
    | '/enquiries/$enquiryId'
    | '/trust/access'
    | '/trust/audit'
    | '/trust/automation'
    | '/enquiries/'
    | '/trust/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/early-access'
    | '/how'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/updates'
    | '/bookings'
    | '/business'
    | '/insights'
    | '/lab'
    | '/settings'
    | '/book/$bookingId'
    | '/q/$enquiryId'
    | '/enquiries/$enquiryId'
    | '/trust/access'
    | '/trust/audit'
    | '/trust/automation'
    | '/enquiries'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/early-access'
    | '/how'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/updates'
    | '/_app/enquiries'
    | '/_app/trust'
    | '/_app/bookings'
    | '/_app/business'
    | '/_app/insights'
    | '/_app/lab'
    | '/_app/settings'
    | '/book/$bookingId'
    | '/q/$enquiryId'
    | '/_app/enquiries/$enquiryId'
    | '/_app/trust/access'
    | '/_app/trust/audit'
    | '/_app/trust/automation'
    | '/_app/enquiries/'
    | '/_app/trust/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  HowRoute: typeof HowRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  TermsRoute: typeof TermsRoute
  UpdatesRoute: typeof UpdatesRoute
  BookBookingIdRoute: typeof BookBookingIdRoute
  QEnquiryIdRoute: typeof QEnquiryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enquiries': {
      id: '/_app/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AppEnquiriesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trust': {
      id: '/_app/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AppTrustRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$bookingId': {
      id: '/book/$bookingId'
      path: '/book/$bookingId'
      fullPath: '/book/$bookingId'
      preLoaderRoute: typeof BookBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$enquiryId': {
      id: '/q/$enquiryId'
      path: '/q/$enquiryId'
      fullPath: '/q/$enquiryId'
      preLoaderRoute: typeof QEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/enquiries/': {
      id: '/_app/enquiries/'
      path: '/'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof AppEnquiriesIndexRouteImport
      parentRoute: typeof AppEnquiriesRouteRoute
    }
    '/_app/enquiries/$enquiryId': {
      id: '/_app/enquiries/$enquiryId'
      path: '/$enquiryId'
      fullPath: '/enquiries/$enquiryId'
      preLoaderRoute: typeof AppEnquiriesEnquiryIdRouteImport
      parentRoute: typeof AppEnquiriesRouteRoute
    }
    '/_app/trust/': {
      id: '/_app/trust/'
      path: '/'
      fullPath: '/trust/'
      preLoaderRoute: typeof AppTrustIndexRouteImport
      parentRoute: typeof AppTrustRouteRoute
    }
    '/_app/trust/access': {
      id: '/_app/trust/access'
      path: '/access'
      fullPath: '/trust/access'
      preLoaderRoute: typeof AppTrustAccessRouteImport
      parentRoute: typeof AppTrustRouteRoute
    }
    '/_app/trust/audit': {
      id: '/_app/trust/audit'
      path: '/audit'
      fullPath: '/trust/audit'
      preLoaderRoute: typeof AppTrustAuditRouteImport
      parentRoute: typeof AppTrustRouteRoute
    }
    '/_app/trust/automation': {
      id: '/_app/trust/automation'
      path: '/automation'
      fullPath: '/trust/automation'
      preLoaderRoute: typeof AppTrustAutomationRouteImport
      parentRoute: typeof AppTrustRouteRoute
    }
  }
}

interface AppEnquiriesRouteRouteChildren {
  AppEnquiriesEnquiryIdRoute: typeof AppEnquiriesEnquiryIdRoute
  AppEnquiriesIndexRoute: typeof AppEnquiriesIndexRoute
}

const AppEnquiriesRouteRouteChildren: AppEnquiriesRouteRouteChildren = {
  AppEnquiriesEnquiryIdRoute: AppEnquiriesEnquiryIdRoute,
  AppEnquiriesIndexRoute: AppEnquiriesIndexRoute,
}

const AppEnquiriesRouteRouteWithChildren =
  AppEnquiriesRouteRoute._addFileChildren(AppEnquiriesRouteRouteChildren)

interface AppTrustRouteRouteChildren {
  AppTrustAccessRoute: typeof AppTrustAccessRoute
  AppTrustAuditRoute: typeof AppTrustAuditRoute
  AppTrustAutomationRoute: typeof AppTrustAutomationRoute
  AppTrustIndexRoute: typeof AppTrustIndexRoute
}

const AppTrustRouteRouteChildren: AppTrustRouteRouteChildren = {
  AppTrustAccessRoute: AppTrustAccessRoute,
  AppTrustAuditRoute: AppTrustAuditRoute,
  AppTrustAutomationRoute: AppTrustAutomationRoute,
  AppTrustIndexRoute: AppTrustIndexRoute,
}

const AppTrustRouteRouteWithChildren = AppTrustRouteRoute._addFileChildren(
  AppTrustRouteRouteChildren,
)

interface AppRouteChildren {
  AppEnquiriesRouteRoute: typeof AppEnquiriesRouteRouteWithChildren
  AppTrustRouteRoute: typeof AppTrustRouteRouteWithChildren
  AppBookingsRoute: typeof AppBookingsRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLabRoute: typeof AppLabRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEnquiriesRouteRoute: AppEnquiriesRouteRouteWithChildren,
  AppTrustRouteRoute: AppTrustRouteRouteWithChildren,
  AppBookingsRoute: AppBookingsRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLabRoute: AppLabRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  HowRoute: HowRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  TermsRoute: TermsRoute,
  UpdatesRoute: UpdatesRoute,
  BookBookingIdRoute: BookBookingIdRoute,
  QEnquiryIdRoute: QEnquiryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
